apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
spec:
  type: LoadBalancer 
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 80         # Porta pública (externa)
      targetPort: 3000 # Porta do container (API)
