name: Deploy para AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login no Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build da imagem Docker
      run: |
        docker build -t simple-api .
        docker tag simple-api:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Push no ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Atualizar serviço no ECS
      run: |
        aws ecs update-service \
          --cluster ecs-simple-api \
          --service simple-api-service \
          --force-new-deployment